// In-memory mock data store for demo mode
// This powers the app when MongoDB is not connected

const MOCK_DATA = {
  citizens: [
    {
      _id: 'citizen_001',
      mockUserId: 'mock_citizen_001',
      governmentId: 'GOV123456789',
      healthId: 'HID-A7X2K',
      fullName: 'Arjun Kumar',
      dateOfBirth: '1970-03-15',
      gender: 'Male',
      bloodGroup: 'B+',
      phone: '+91-9876543210',
      email: 'citizen@demo.com',
      address: '45, Nehru Nagar, New Delhi - 110001',
      emergencyContact: { name: 'Sunita Kumar', phone: '+91-9988776655', relationship: 'Spouse' },
      isVerified: true,
      isBlocked: false,
      createdAt: '2020-01-15',
    },
    {
      _id: 'citizen_002',
      governmentId: 'GOV987654321',
      healthId: 'HID-B3R9M',
      fullName: 'Meera Patel',
      dateOfBirth: '1985-07-22',
      gender: 'Female',
      bloodGroup: 'O+',
      phone: '+91-9123456789',
      email: 'meera.patel@email.com',
      address: '12, Gandhi Road, Mumbai - 400001',
      isVerified: true,
      isBlocked: false,
      createdAt: '2021-03-20',
    },
    {
      _id: 'citizen_003',
      governmentId: 'GOV112233445',
      healthId: 'HID-C5T7P',
      fullName: 'Suresh Reddy',
      dateOfBirth: '1955-11-08',
      gender: 'Male',
      bloodGroup: 'A-',
      phone: '+91-9654321098',
      email: 'suresh.reddy@email.com',
      address: '78, MG Road, Bangalore - 560001',
      isVerified: true,
      isBlocked: false,
      createdAt: '2019-06-10',
    },
  ],

  doctors: [
    {
      _id: 'doctor_001',
      mockUserId: 'mock_doctor_001',
      fullName: 'Dr. Priya Sharma',
      email: 'doctor@demo.com',
      phone: '+91-9811223344',
      medicalLicenseNumber: 'MCI-DL-2019-04521',
      specialization: 'Internal Medicine',
      hospitalName: 'AIIMS New Delhi',
      department: 'General Medicine',
      status: 'approved',
      verifiedAt: '2024-01-10',
      isDiagnosticCenter: false,
    },
    {
      _id: 'doctor_002',
      mockUserId: 'mock_diag_001',
      fullName: 'Dr. Rajesh Mehta',
      email: 'diagnostic@demo.com',
      phone: '+91-9922334455',
      medicalLicenseNumber: 'MCI-DL-2018-03312',
      specialization: 'Radiology',
      hospitalName: 'Apollo Diagnostics Center',
      department: 'Radiology',
      status: 'approved',
      verifiedAt: '2024-02-05',
      isDiagnosticCenter: true,
    },
    {
      _id: 'doctor_003',
      fullName: 'Dr. Kavita Singh',
      email: 'kavita.singh@hospital.com',
      medicalLicenseNumber: 'MCI-MH-2020-07891',
      specialization: 'Cardiology',
      hospitalName: 'Fortis Hospital Mumbai',
      department: 'Cardiology',
      status: 'pending',
    },
    {
      _id: 'doctor_004',
      fullName: 'Dr. Amit Verma',
      email: 'amit.verma@clinic.com',
      medicalLicenseNumber: 'MCI-KA-2017-02234',
      specialization: 'Orthopedics',
      hospitalName: 'Narayana Health Bangalore',
      department: 'Orthopedics',
      status: 'rejected',
      rejectionReason: 'License certificate not legible. Please resubmit.',
    },
  ],

  hospitals: [
    {
      _id: 'hospital_001',
      registrationNumber: 'DH-REG-2015-00123',
      name: 'AIIMS New Delhi',
      type: 'Government',
      address: 'Sri Aurobindo Marg, Ansari Nagar, New Delhi - 110029',
      contactPhone: '+91-11-26588500',
      contactEmail: 'info@aiims.edu',
      status: 'approved',
      verifiedAt: '2015-06-01',
    },
    {
      _id: 'hospital_002',
      registrationNumber: 'APOLLO-DIA-2018-00456',
      name: 'Apollo Diagnostics Center',
      type: 'Diagnostic Center',
      address: 'Saket District Centre, New Delhi - 110017',
      contactPhone: '+91-11-29871234',
      contactEmail: 'info@apollodiag.com',
      status: 'approved',
      verifiedAt: '2018-03-15',
    },
    {
      _id: 'hospital_003',
      registrationNumber: 'FORTIS-MH-2019-00789',
      name: 'Fortis Hospital Mumbai',
      type: 'Private',
      address: 'Mulund Goregaon Link Road, Mumbai - 400078',
      contactPhone: '+91-22-67670000',
      contactEmail: 'info@fortishealthcare.com',
      status: 'pending',
    },
  ],

  records: [
    {
      _id: 'record_001',
      patientId: 'citizen_001',
      uploadedBy: 'doctor_002',
      hospitalName: 'Apollo Diagnostics Center',
      doctorName: 'Dr. Rajesh Mehta',
      doctorSpecialization: 'Radiology',
      type: 'scan',
      scanType: 'MRI',
      bodyPart: 'Brain',
      reportTitle: 'MRI Brain — Routine Checkup',
      reportText: 'MRI of the brain with and without contrast. The brain parenchyma appears normal. No acute infarction, hemorrhage, or mass lesion. Ventricles and sulci are normal in size and configuration. No abnormal enhancement noted. IMPRESSION: Normal MRI Brain.',
      aiSummary: {
        criticalAlerts: ['Allergy: Penicillin (Anaphylaxis)', 'Warfarin 5mg (Blood thinner)'],
        chronicConditions: ['Type 2 Diabetes (HbA1c 7.8%)', 'Hypertension Stage 2'],
        minorHistory: ['URTI Jan 2023', 'Gastritis Mar 2022'],
        snapshot: '55yo male with T2DM, HTN. Allergic to Penicillin. On Warfarin. Normal brain MRI.',
      },
      recordDate: '2024-11-15',
      uploadedAt: '2024-11-15',
    },
    {
      _id: 'record_002',
      patientId: 'citizen_001',
      uploadedBy: 'doctor_001',
      hospitalName: 'AIIMS New Delhi',
      doctorName: 'Dr. Priya Sharma',
      doctorSpecialization: 'Internal Medicine',
      type: 'lab_report',
      reportTitle: 'Complete Blood Count + HbA1c Panel',
      reportText: 'CBC: WBC 7.2 x10³/µL (Normal), RBC 4.5 x10⁶/µL (Normal), Hemoglobin 13.8 g/dL (Normal), Platelets 245 x10³/µL (Normal). HbA1c: 7.8% (Target <7.0% for T2DM — Suboptimal). Fasting Glucose: 145 mg/dL (High). Lipid Panel: LDL 128 mg/dL, HDL 42 mg/dL. IMPRESSION: Suboptimal glycemic control. Medication review recommended.',
      recordDate: '2024-09-20',
      uploadedAt: '2024-09-20',
    },
    {
      _id: 'record_003',
      patientId: 'citizen_001',
      uploadedBy: 'doctor_001',
      hospitalName: 'AIIMS New Delhi',
      doctorName: 'Dr. Priya Sharma',
      doctorSpecialization: 'Internal Medicine',
      type: 'prescription',
      reportTitle: 'Prescription — Hypertension & Diabetes Management',
      reportText: '1. Metformin 500mg BD (Continue)\n2. Amlodipine 5mg OD (Continue)\n3. Warfarin 5mg OD (Continue — INR monitoring monthly)\n4. Aspirin 75mg OD (Antiplatelet)\n5. Atorvastatin 20mg OD (Cholesterol)\nNext review: 3 months. Monitor: BP, fasting glucose, INR.',
      consultationNotes: 'Patient BP 148/92 today. Advised dietary modifications, salt restriction. Increased Amlodipine from 2.5mg to 5mg.',
      recordDate: '2024-09-20',
      uploadedAt: '2024-09-20',
    },
    {
      _id: 'record_004',
      patientId: 'citizen_001',
      uploadedBy: 'doctor_002',
      hospitalName: 'Apollo Diagnostics Center',
      doctorName: 'Dr. Rajesh Mehta',
      doctorSpecialization: 'Radiology',
      type: 'scan',
      scanType: 'Chest X-Ray',
      bodyPart: 'Chest',
      reportTitle: 'Chest X-Ray PA View — Annual Screening',
      reportText: 'PA chest radiograph: Cardiac size normal. Lungs are clear. No consolidation, pneumothorax, or pleural effusion. Costophrenic angles are sharp. Diaphragm normal. Bony thorax unremarkable. IMPRESSION: Normal chest X-Ray.',
      recordDate: '2024-06-10',
      uploadedAt: '2024-06-10',
    },
    {
      _id: 'record_005',
      patientId: 'citizen_001',
      uploadedBy: 'doctor_001',
      hospitalName: 'AIIMS New Delhi',
      doctorName: 'Dr. Priya Sharma',
      doctorSpecialization: 'Internal Medicine',
      type: 'lab_report',
      reportTitle: 'Renal Function Test + Electrolytes',
      reportText: 'Serum Creatinine: 1.1 mg/dL (Normal). BUN: 18 mg/dL (Normal). eGFR: 68 mL/min/1.73m² (Stage 2 CKD — borderline). Sodium: 138 mEq/L, Potassium: 4.2 mEq/L (Normal). IMPRESSION: Borderline kidney function — monitor every 6 months.',
      recordDate: '2024-03-05',
      uploadedAt: '2024-03-05',
    },
    {
      _id: 'record_006',
      patientId: 'citizen_001',
      uploadedBy: 'doctor_001',
      hospitalName: 'AIIMS New Delhi',
      doctorName: 'Dr. Priya Sharma',
      doctorSpecialization: 'Internal Medicine',
      type: 'consultation',
      reportTitle: 'URTI — Resolved',
      reportText: 'Patient presents with 3-day history of runny nose, mild sore throat, low-grade fever (99.2°F). Throat: mild erythema. Lungs clear. DIAGNOSIS: Viral Upper Respiratory Tract Infection. TREATMENT: Paracetamol 500mg TID x 3 days, throat lozenges, rest. AVOID: Penicillin (documented allergy). FOLLOW-UP: As needed.',
      recordDate: '2023-01-12',
      uploadedAt: '2023-01-12',
    },
  ],

  auditLogs: [
    {
      _id: 'audit_001',
      actorId: 'mock_doctor_001',
      actorName: 'Dr. Priya Sharma',
      actorRole: 'doctor',
      action: 'RECORD_VIEW',
      targetPatientId: 'citizen_001',
      targetPatientName: 'Arjun Kumar',
      details: 'Viewed CBC + HbA1c report via QR session',
      isEmergency: false,
      timestamp: '2024-11-20T10:30:00Z',
    },
    {
      _id: 'audit_002',
      actorId: 'mock_diag_001',
      actorName: 'Dr. Rajesh Mehta',
      actorRole: 'diagnostic',
      action: 'RECORD_UPLOAD',
      targetPatientId: 'citizen_001',
      targetPatientName: 'Arjun Kumar',
      details: 'Uploaded MRI Brain scan report',
      isEmergency: false,
      timestamp: '2024-11-15T09:15:00Z',
    },
    {
      _id: 'audit_003',
      actorId: 'mock_doctor_001',
      actorName: 'Dr. Priya Sharma',
      actorRole: 'doctor',
      action: 'EMERGENCY_ACCESS_GRANT',
      targetPatientId: 'citizen_001',
      targetPatientName: 'Arjun Kumar',
      details: 'Emergency override — Reason: Cardiac Arrest. 15-min access granted.',
      isEmergency: true,
      isFlagged: false,
      timestamp: '2024-10-05T02:45:00Z',
    },
    {
      _id: 'audit_004',
      actorId: 'mock_citizen_001',
      actorName: 'Arjun Kumar',
      actorRole: 'citizen',
      action: 'QR_GENERATE',
      targetPatientId: 'citizen_001',
      targetPatientName: 'Arjun Kumar',
      details: 'Generated QR — Sharing level: Emergency Only — Duration: 30 min',
      isEmergency: false,
      timestamp: '2024-09-28T14:20:00Z',
    },
  ],

  notifications: [
    {
      _id: 'notif_001',
      type: 'emergency_access',
      title: '⚠️ Emergency Access Alert',
      message: 'Dr. Priya Sharma accessed your records under emergency protocol on Oct 5, 2024.',
      isRead: false,
      timestamp: '2024-10-05T02:45:00Z',
      severity: 'high',
    },
    {
      _id: 'notif_002',
      type: 'new_record',
      title: '📋 New Record Added',
      message: 'Dr. Rajesh Mehta uploaded your MRI Brain scan report from Apollo Diagnostics.',
      isRead: true,
      timestamp: '2024-11-15T09:15:00Z',
      severity: 'info',
    },
    {
      _id: 'notif_003',
      type: 'qr_scanned',
      title: '🔍 QR Code Scanned',
      message: 'Dr. Priya Sharma scanned your health QR code on Nov 20, 2024.',
      isRead: true,
      timestamp: '2024-11-20T10:30:00Z',
      severity: 'medium',
    },
    {
      _id: 'notif_004',
      type: 'record_uploaded',
      title: '📁 Lab Report Available',
      message: 'Your Renal Function Test results are now available in your health passport.',
      isRead: false,
      timestamp: '2024-03-05T11:00:00Z',
      severity: 'info',
    },
  ],

  qrSessions: [],
  emergencyAccesses: [],
};

module.exports = { MOCK_DATA };
